[package]
name = "dverf_device"
version = "0.1.0"
edition.workspace = true

[dependencies]
thiserror.workspace = true
futures-lite.workspace = true

nusb = { version = "0.1" }
num_enum = { version = "0.7" }
futures-sink = { version = "0.3" }
