[package]
name = "simple_receive"
version = "0.1.0"
edition.workspace = true

[dependencies]
dverf_device.workspace = true
anyhow.workspace = true
futures-lite.workspace = true
futures-concurrency = { version = "7" }

nusb = { version = "0.1" }